export default [
    {
        "id":1794,
        "name":"FrankfurtToHongkong_800Mbps",
        "vlan":2,
        "nni_vlan":null,
        "created":"2018-10-16 13:36:46",
        "expires":"2020-10-15 13:37:02",
        "protected":"Network Protected",
        "bandwidth":"800Mbps",
        "paused":false,
        "expired":false,
        "manual_service":false,
        "type":"Inter-port Connection",
        "type_short_name":"INT",
        "service_town":"",
        "status":"in service",
        "port":{
            "id":933,
            "ref":"clxp-TgBiSMdm",
            "name":"Frankfurt Port",
            "datacentre_name":"FFT-Demo-1 - B72 1\/1\/G11",
            "index":10,
            "speed":"1Gbit",
            "throughput":1000000,
            "committed_bandwidth":"1,000Mb\/sec",
            "committed_bandwidth_raw":1000000,
            "remaining_bandwidth":"0Mb\/sec",
            "remaining_bandwidth_raw":0,
            "utilisation":"100%",
            "utilisation_raw":"100",
            "customer":"ACME Corp",
            "customer_id":354,
            "odf_position":"ODF 1 Block B Ports 1\/32",
            "regions":[{"name":"Frankfurt"},{"name":"Germany"},{"name":"Europe"},{"name":"Global"}],
            "switch":{"id":85,"index":1},
            "slot":{"id":83,"index":1},
            "shelf":{"id":77,"index":1,"name":"FFT Demo 1"},
            "shelf_type":"DUMMY",
            "network_alarms":[],
            "services":[
                {"id":1794,"name":"FrankfurtToHongkong_800Mbps"},
                {"id":1796,"name":"FranFurtToDECIX_200Mbps"}
                ],
            "service_type":{
                "id":20,
                "name":"Inter-port Connection",
                "short_name":"INT",
                "logo_path":null,
                "regions":"",
                "category":"INT",
                "category_id":3
            },
            "service_count":2,
            "single_use":0,
            "offnet_supplier_ref":"",
            "offnet_supplier_ref_display":null,
            "offnet_service_ref":"",
            "offnet_service_ref_display":null,
            "service_town":null,
            "user_can_access":true,
            "datacentre_datacentre_name":"Equinix FR7",
            "datacentre_logo":"\/clx\/datacentre-groups\/2\/datacentre-group\/logo?realm=clx?_1537881614",
            "datacentre_city":"Frankfurt",
            "datacentre_city_iso":"DE",
            "disabled":false,
            "disabled_reason":null,
            "status":"in service"
        },
        "b_port":{
            "id":1434,
            "ref":"clxp-fq9FqktN",
            "name":"Hong Kong Port",
            "datacentre_name":"EPHK-MEG1DEMO1 (10GE)",
            "index":12,
            "speed":"10Gbit",
            "throughput":10000000,
            "committed_bandwidth":"4,850Mb\/sec",
            "committed_bandwidth_raw":4850000,
            "remaining_bandwidth":"5,150Mb\/sec",
            "remaining_bandwidth_raw":5150000,
            "utilisation":"48.5%",
            "utilisation_raw":"48.5",
            "customer":"ACME Corp",
            "customer_id":354,
            "odf_position":"ODF 1 Block B Ports 3\/5",
            "regions":[{"name":"Hong Kong"},{"name":"Global"}],
            "switch":{"id":102,"index":1},
            "slot":{"id":95,"index":2},
            "shelf":{"id":88,"index":2,"name":"EPHK-MEG1-DEMO1"},
            "shelf_type":"DUMMY",
            "network_alarms":[],
            "services":[
                {"id":1795,"name":"HongkongToNYC_4Gbps"},
                {"id":1797,"name":"NYC_to_Azure_London_50Mbps"},
                {"id":1794,"name":"FrankfurtToHongkong_800Mbps"}
                ],
            "service_type":{
                "id":20,"name":"Inter-port Connection",
                "short_name":"INT",
                "logo_path":null,
                "regions":"",
                "category":"INT",
                "category_id":3
            },
            "service_count":3,
            "single_use":0,
            "offnet_supplier_ref":"",
            "offnet_supplier_ref_display":null,
            "offnet_service_ref":"",
            "offnet_service_ref_display":null,
            "service_town":null,
            "user_can_access":true,
            "datacentre_datacentre_name":"Mega-iAdvantage",
            "datacentre_logo":"\/clx\/datacentre-groups\/16\/datacentre-group\/logo?realm=clx?_1530089912",
            "datacentre_city":"Hong Kong",
            "datacentre_city_iso":"HK",
            "disabled":false,
            "disabled_reason":null,
            "status":"in service"
        }
    },
    {
        "id":1795,
        "name":"HongkongToNYC_4Gbps",
        "vlan":7,
        "nni_vlan":null,"created":"2018-10-16 13:39:13","expires":"2020-01-10 13:43:03","protected":"Unprotected","bandwidth":"4000Mbps","paused":false,"expired":false,"manual_service":false,"type":"Inter-port Connection","type_short_name":"INT","service_town":"","status":"in service","port":{"id":1434,"ref":"clxp-fq9FqktN","name":"Hong Kong Port","datacentre_name":"EPHK-MEG1DEMO1 (10GE)","index":12,"speed":"10Gbit","throughput":10000000,"committed_bandwidth":"4,850Mb\/sec","committed_bandwidth_raw":4850000,"remaining_bandwidth":"5,150Mb\/sec","remaining_bandwidth_raw":5150000,"utilisation":"48.5%","utilisation_raw":"48.5","customer":"ACME Corp","customer_id":354,"odf_position":"ODF 1 Block B Ports 3\/5","regions":[{"name":"Hong Kong"},{"name":"Global"}],"switch":{"id":102,"index":1},"slot":{"id":95,"index":2},"shelf":{"id":88,"index":2,"name":"EPHK-MEG1-DEMO1"},"shelf_type":"DUMMY","network_alarms":[],"services":[{"id":1795,"name":"HongkongToNYC_4Gbps"},{"id":1797,"name":"NYC_to_Azure_London_50Mbps"},{"id":1794,"name":"FrankfurtToHongkong_800Mbps"}],"service_type":{"id":20,"name":"Inter-port Connection","short_name":"INT","logo_path":null,"regions":"","category":"INT","category_id":3},"service_count":3,"single_use":0,"offnet_supplier_ref":"","offnet_supplier_ref_display":null,"offnet_service_ref":"","offnet_service_ref_display":null,"service_town":null,"user_can_access":true,"datacentre_datacentre_name":"Mega-iAdvantage","datacentre_logo":"\/clx\/datacentre-groups\/16\/datacentre-group\/logo?realm=clx?_1530089912","datacentre_city":"Hong Kong","datacentre_city_iso":"HK","disabled":false,"disabled_reason":null,"status":"in service"},"b_port":{"id":1474,"ref":"clxp-xy84Vedt","name":"New York City Port","datacentre_name":"EPUS-EHS1-DEMO2 (10GE)","index":12,"speed":"10Gbit","throughput":10000000,"committed_bandwidth":"4,050Mb\/sec","committed_bandwidth_raw":4050000,"remaining_bandwidth":"5,950Mb\/sec","remaining_bandwidth_raw":5950000,"utilisation":"40.5%","utilisation_raw":"40.5","customer":"ACME Corp","customer_id":354,"odf_position":"ODF 1 Block B Ports 3\/5","regions":[{"name":"New York"},{"name":"US East"},{"name":"United States"},{"name":"Global"}],"switch":{"id":103,"index":1},"slot":{"id":96,"index":2},"shelf":{"id":89,"index":2,"name":"EPUS-EHS1-DEMO2"},"shelf_type":"DUMMY","network_alarms":[],"services":[{"id":1798,"name":"NYC_to_Azure_London_50Mbps"},{"id":1795,"name":"HongkongToNYC_4Gbps"}],"service_type":{"id":20,"name":"Inter-port Connection","short_name":"INT","logo_path":null,"regions":"","category":"INT","category_id":3},"service_count":2,"single_use":0,"offnet_supplier_ref":"","offnet_supplier_ref_display":null,"offnet_service_ref":"","offnet_service_ref_display":null,"service_town":null,"user_can_access":true,"datacentre_datacentre_name":"Epsilon Global Hubs 60","datacentre_logo":"\/clx\/datacentre-groups\/8\/datacentre-group\/logo?realm=clx?_1530024260","datacentre_city":"New York City","datacentre_city_iso":"US","disabled":false,"disabled_reason":null,"status":"in service"}},{"id":1796,"name":"FranFurtToDECIX_200Mbps","vlan":8,"nni_vlan":null,"created":"2018-10-16 13:43:59","expires":"2018-11-16 13:43:59","protected":"Unprotected","bandwidth":"200Mbps","paused":false,"expired":false,"manual_service":false,"type":"DE-CIX","type_short_name":"DEC","service_town":"New York","status":"in service","port":{"id":933,"ref":"clxp-TgBiSMdm","name":"Frankfurt Port","datacentre_name":"FFT-Demo-1 - B72 1\/1\/G11","index":10,"speed":"1Gbit","throughput":1000000,"committed_bandwidth":"1,000Mb\/sec","committed_bandwidth_raw":1000000,"remaining_bandwidth":"0Mb\/sec","remaining_bandwidth_raw":0,"utilisation":"100%","utilisation_raw":"100","customer":"ACME Corp","customer_id":354,"odf_position":"ODF 1 Block B Ports 1\/32","regions":[{"name":"Frankfurt"},{"name":"Germany"},{"name":"Europe"},{"name":"Global"}],"switch":{"id":85,"index":1},"slot":{"id":83,"index":1},"shelf":{"id":77,"index":1,"name":"FFT Demo 1"},"shelf_type":"DUMMY","network_alarms":[],"services":[{"id":1794,"name":"FrankfurtToHongkong_800Mbps"},{"id":1796,"name":"FranFurtToDECIX_200Mbps"}],"service_type":{"id":20,"name":"Inter-port Connection","short_name":"INT","logo_path":null,"regions":"","category":"INT","category_id":3},"service_count":2,"single_use":0,"offnet_supplier_ref":"","offnet_supplier_ref_display":null,"offnet_service_ref":"","offnet_service_ref_display":null,"service_town":null,"user_can_access":true,"datacentre_datacentre_name":"Equinix FR7","datacentre_logo":"\/clx\/datacentre-groups\/2\/datacentre-group\/logo?realm=clx?_1537881614","datacentre_city":"Frankfurt","datacentre_city_iso":"DE","disabled":false,"disabled_reason":null,"status":"in service"}},{"id":1798,"name":"NYC_to_Azure_London_50Mbps","vlan":10,"nni_vlan":null,"created":"2018-10-16 13:57:18","expires":"2020-10-15 13:58:03","protected":"Unprotected","bandwidth":"50Mbps","paused":false,"expired":false,"manual_service":false,"type":"Microsoft Azure","type_short_name":"MSA","service_town":"London","status":"down","port":{"id":1474,"ref":"clxp-xy84Vedt","name":"New York City Port","datacentre_name":"EPUS-EHS1-DEMO2 (10GE)","index":12,"speed":"10Gbit","throughput":10000000,"committed_bandwidth":"4,050Mb\/sec","committed_bandwidth_raw":4050000,"remaining_bandwidth":"5,950Mb\/sec","remaining_bandwidth_raw":5950000,"utilisation":"40.5%","utilisation_raw":"40.5","customer":"ACME Corp","customer_id":354,"odf_position":"ODF 1 Block B Ports 3\/5","regions":[{"name":"New York"},{"name":"US East"},{"name":"United States"},{"name":"Global"}],"switch":{"id":103,"index":1},"slot":{"id":96,"index":2},"shelf":{"id":89,"index":2,"name":"EPUS-EHS1-DEMO2"},"shelf_type":"DUMMY","network_alarms":[],"services":[{"id":1798,"name":"NYC_to_Azure_London_50Mbps"},{"id":1795,"name":"HongkongToNYC_4Gbps"}],"service_type":{"id":20,"name":"Inter-port Connection","short_name":"INT","logo_path":null,"regions":"","category":"INT","category_id":3},"service_count":2,"single_use":0,"offnet_supplier_ref":"","offnet_supplier_ref_display":null,"offnet_service_ref":"","offnet_service_ref_display":null,"service_town":null,"user_can_access":true,"datacentre_datacentre_name":"Epsilon Global Hubs 60","datacentre_logo":"\/clx\/datacentre-groups\/8\/datacentre-group\/logo?realm=clx?_1530024260","datacentre_city":"New York City","datacentre_city_iso":"US","disabled":false,"disabled_reason":null,"status":"in service"},"secondary_service":{"id":1797,"name":"NYC_to_Azure_London_50Mbps","vlan":10,"nni_vlan":null,"created":"2018-10-16 13:57:18","expires":"2020-10-15 13:58:02","protected":"Unprotected","bandwidth":"50Mbps","paused":false,"expired":false,"manual_service":false,"type":"Microsoft Azure","type_short_name":"MSA","service_town":"London","status":"provisioning","port":{"id":1434,"ref":"clxp-fq9FqktN","name":"Hong Kong Port","datacentre_name":"EPHK-MEG1DEMO1 (10GE)","index":12,"speed":"10Gbit","throughput":10000000,"committed_bandwidth":"4,850Mb\/sec","committed_bandwidth_raw":4850000,"remaining_bandwidth":"5,150Mb\/sec","remaining_bandwidth_raw":5150000,"utilisation":"48.5%","utilisation_raw":"48.5","customer":"ACME Corp","customer_id":354,"odf_position":"ODF 1 Block B Ports 3\/5","regions":[{"name":"Hong Kong"},{"name":"Global"}],"switch":{"id":102,"index":1},"slot":{"id":95,"index":2},"shelf":{"id":88,"index":2,"name":"EPHK-MEG1-DEMO1"},"shelf_type":"DUMMY","network_alarms":[],"services":[{"id":1795,"name":"HongkongToNYC_4Gbps"},{"id":1797,"name":"NYC_to_Azure_London_50Mbps"},{"id":1794,"name":"FrankfurtToHongkong_800Mbps"}],"service_type":{"id":20,"name":"Inter-port Connection","short_name":"INT","logo_path":null,"regions":"","category":"INT","category_id":3},"service_count":3,"single_use":0,"offnet_supplier_ref":"","offnet_supplier_ref_display":null,"offnet_service_ref":"","offnet_service_ref_display":null,"service_town":null,"user_can_access":true,"datacentre_datacentre_name":"Mega-iAdvantage","datacentre_logo":"\/clx\/datacentre-groups\/16\/datacentre-group\/logo?realm=clx?_1530089912","datacentre_city":"Hong Kong","datacentre_city_iso":"HK","disabled":false,"disabled_reason":null,"status":"in service"}}}]
